// Orchestrates one task end-to-end:
// issue → worktree → agent → commit → push → PR.
import * as git from './git.js'
import * as gh from './github.js'
import * as questions from './questions.js'
import { runAgent } from './agent.js'
import { updateTask, addEvent } from './tasks.js'

const controllers = new Map() // taskId -> AbortController

export function cancel(taskId) {
  questions.clear(taskId) // unpark the agent if it's waiting on an answer
  const ac = controllers.get(taskId)
  if (ac) { ac.abort(); return true }
  return false
}

function buildPrompt(owner, repo, issue) {
  return `You are an autonomous software engineer working in a fresh git worktree of the repository ${owner}/${repo}. The full repository is checked out in your current working directory.

Resolve this GitHub issue with a focused, complete, production-quality change:

--- ISSUE #${issue.number}: ${issue.title} ---
${issue.body || '(no description provided)'}
--- END ISSUE ---

Guidelines:
- Begin by reading README / CLAUDE.md / AGENTS.md and the relevant code to learn the project's conventions, THEN implement.
- Make the minimal set of changes that fully resolves the issue. Match the existing style and structure.
- If the project has a test suite, run it; add or update tests where it makes sense.
- Prefer reasonable assumptions and keep moving — note any notable assumptions in your final summary.
- Only if a wrong guess would be expensive or irreversible, call the \`ask_user\` tool to ask the operator and wait for their reply.
- Do NOT commit, push, or open a pull request — the harness handles git. Just leave your finished changes saved in the working tree.
- End with a short summary (2-4 sentences) describing what you changed and why.`
}

function prBody(issueNumber, summary) {
  return `${summary || 'Automated change.'}

Resolves #${issueNumber}

---
🤖 Generated by Squadron with Claude Code`
}

export async function dispatch(task, { defaultBranch } = {}) {
  const { id, owner, repo, issueNumber, model } = task
  const ac = new AbortController()
  controllers.set(id, ac)
  const log = (kind, text, extra = {}) => addEvent(id, { kind, text, ...extra })

  try {
    await updateTask(id, { status: 'preparing' })
    log('status', `Fetching issue #${issueNumber}…`)
    const issue = await gh.getIssue(owner, repo, issueNumber)

    log('status', 'Cloning / preparing isolated worktree…')
    const { path: wt, branch, base } = await git.createWorktree(owner, repo, id, defaultBranch)
    await updateTask(id, { branch, base, status: 'running' })
    log('status', `Agent working on branch ${branch}`)

    const result = await runAgent({
      prompt: buildPrompt(owner, repo, issue),
      cwd: wt,
      model,
      signal: ac.signal,
      onEvent: (e) => addEvent(id, e),
      askUser: async (question) => {
        addEvent(id, { kind: 'question', text: question })
        await updateTask(id, { status: 'waiting', question })
        const reply = await questions.register(id)
        await updateTask(id, { status: 'running', question: null })
        addEvent(id, { kind: 'answer', text: reply })
        return reply
      },
    })

    if (ac.signal.aborted) {
      log('status', 'Cancelled by user.')
      await updateTask(id, { status: 'cancelled', summary: result.summary })
      await git.removeWorktree(owner, repo, id)
      return
    }

    log('status', 'Committing changes…')
    await updateTask(id, { status: 'committing', summary: result.summary, costUsd: result.costUsd })
    const committed = await git.commitAll(wt, `${issue.title}\n\nResolves #${issueNumber}`)

    if (!committed) {
      log('status', 'Agent produced no file changes — nothing to push.')
      await updateTask(id, { status: 'no_changes' })
      await git.removeWorktree(owner, repo, id)
      return
    }

    log('status', 'Pushing branch to origin…')
    await updateTask(id, { status: 'pushing' })
    await git.pushBranch(wt, branch)

    log('status', 'Opening pull request…')
    await updateTask(id, { status: 'opening_pr' })
    const prUrl = await gh.createPr(owner, repo, {
      head: branch, base, title: issue.title, body: prBody(issueNumber, result.summary),
    })

    await updateTask(id, { status: 'pr_open', prUrl })
    log('result', `Pull request opened → ${prUrl}`, { ok: true })
    await git.removeWorktree(owner, repo, id)
  } catch (err) {
    console.error(`[task ${id}]`, err)
    log('error', err.message)
    await updateTask(id, { status: 'error', error: err.message })
    await git.removeWorktree(owner, repo, id).catch(() => {})
  } finally {
    controllers.delete(id)
  }
}
