// Task lifecycle: interactive PLAN (read-only chat) → operator approves →
// one-shot EXECUTION in the same worktree → commit → push → PR.
import * as git from './git.js'
import * as gh from './github.js'
import * as questions from './questions.js'
import { openSession, runExecution, describeTool } from './agent.js'
import { updateTask, addEvent, getTask } from './tasks.js'

const sessions = new Map() // taskId -> ctx

const PLAN_INSTRUCTIONS = `You are scoping a GitHub issue for an autonomous engineer who will implement it right after you. Investigate the codebase (read-only) and produce a clear, concrete implementation plan: the approach, the specific files/functions to change, and any tests to add. Keep it tight and skimmable — markdown, a handful of bullets. The operator reviews your plan in a chat and may ask for revisions; incorporate their feedback and restate the updated plan.

Operating rules (important):
- You are already in the repository root. Use relative paths only; never cd elsewhere or access paths outside this directory.
- Present the plan directly as your reply. Do NOT write it to a file, do NOT call ExitPlanMode or AskUserQuestion, and do NOT discuss which tools are or aren't available.
- To ask the operator a question, simply write it in your message — they reply in the chat. The operator approves and triggers execution separately.`

function planFirstMessage(owner, repo, issue) {
  return `You are scoping work in the repository ${owner}/${repo}. The repo is checked out in your current working directory (read-only for now).

IMPORTANT: Stay strictly inside your current working directory. Use relative paths only. Do NOT cd elsewhere, reference absolute paths to other locations, or search the wider filesystem — those attempts are blocked and waste turns. Everything you need is right here.

Investigate the relevant code and propose a concrete implementation plan for this issue. Keep it tight and skimmable.

--- ISSUE #${issue.number}: ${issue.title} ---
${issue.body || '(no description provided)'}
--- END ISSUE ---`
}

function executePrompt(owner, repo, issue, plan) {
  return `You are an autonomous engineer working in a fresh git worktree of ${owner}/${repo}. The repo is checked out in your working directory.

Implement the following approved plan to resolve issue #${issue.number} ("${issue.title}"). Follow the plan; use judgement on the details.

--- APPROVED PLAN ---
${plan}
--- END PLAN ---

Guidelines:
- You are already at the repository root. Use relative paths only; never cd elsewhere or touch other locations — those attempts are blocked and waste turns.
- Match the project's existing style and conventions.
- If there's a test suite, run it; add or update tests where sensible.
- Only call the \`ask_user\` tool if a wrong guess would be expensive or irreversible.
- Do NOT commit, push, or open a pull request — the harness handles git. Leave your finished changes saved in the working tree.
- End with a 2-4 sentence summary of what you changed and why.`
}

function prBody(issue, summary, plan) {
  return `${summary || 'Automated change.'}

Resolves #${issue.number}

<details><summary>📋 Approved plan</summary>

${plan || '(none)'}
</details>

---
🤖 Generated by Squadron with Claude Code`
}

// --- Plan phase ---

export async function startPlan(task, { defaultBranch } = {}) {
  const { id, owner, repo, issueNumber, model } = task
  try {
    await updateTask(id, { status: 'preparing' })
    addEvent(id, { kind: 'status', text: `Fetching issue #${issueNumber}…` })
    const issue = await gh.getIssue(owner, repo, issueNumber)

    addEvent(id, { kind: 'status', text: 'Preparing isolated worktree…' })
    const { path: wt, branch, base } = await git.createWorktree(owner, repo, id, defaultBranch)
    await updateTask(id, { branch, base, status: 'planning' })

    const ctx = { id, owner, repo, issue, wt, branch, base, model, phase: 'planning', lastText: '', plan: '' }
    sessions.set(id, ctx)

    const handle = await openSession({
      cwd: wt, model, permissionMode: 'plan', planModeInstructions: PLAN_INSTRUCTIONS,
      onMessage: (m) => onPlanMessage(ctx, m),
    })
    ctx.handle = handle
    handle.send(planFirstMessage(owner, repo, issue))
  } catch (err) {
    console.error(`[plan ${id}]`, err)
    addEvent(id, { kind: 'error', text: err.message })
    await updateTask(id, { status: 'error', error: err.message })
    sessions.delete(id)
  }
}

function onPlanMessage(ctx, m) {
  const { id } = ctx
  if (ctx.phase !== 'planning') return // execution messages are handled by runExecution
  switch (m.type) {
    case 'system':
      if (m.subtype === 'init') addEvent(id, { kind: 'status', text: `planner online · ${m.model || ctx.model}` })
      break
    case 'assistant':
      for (const b of m.message?.content ?? []) {
        if (b.type === 'text' && b.text?.trim()) { ctx.lastText = b.text.trim(); addEvent(id, { kind: 'text', text: ctx.lastText }) }
        else if (b.type === 'tool_use') {
          if (b.name === 'ExitPlanMode' && b.input?.plan) { ctx.lastText = b.input.plan }
          else addEvent(id, { kind: 'tool', text: describeTool(b) })
        }
      }
      break
    case 'result':
      // a plan turn finished — capture the latest plan and await the operator
      ctx.plan = ctx.lastText
      updateTask(id, { status: 'planned', plan: ctx.plan })
      break
  }
}

export function sendMessage(taskId, text) {
  const ctx = sessions.get(taskId)
  if (!ctx || ctx.phase !== 'planning') return false
  addEvent(taskId, { kind: 'user', text })
  updateTask(taskId, { status: 'planning' })
  ctx.handle.send(text)
  return true
}

// --- Execution phase ---

export async function approve(taskId) {
  const task0 = await getTask(taskId)
  // Review tasks: "approve" means post the review to the PR.
  if ((sessions.get(taskId)?.kind || task0?.kind) === 'review') return approveReview(taskId, task0)

  let ctx = sessions.get(taskId)

  // If the planning session was lost (e.g. the server restarted), rebuild just
  // enough context from the persisted task to execute the captured plan.
  if (!ctx) {
    const task = await getTask(taskId)
    if (!task || task.status !== 'planned' || !task.plan || !task.branch) return false
    if (!(await git.worktreeExists(taskId))) {
      addEvent(taskId, { kind: 'error', text: 'Worktree no longer exists — re-plan this issue.' })
      await updateTask(taskId, { status: 'interrupted' })
      return false
    }
    addEvent(taskId, { kind: 'status', text: 'Resuming after restart — re-fetching issue…' })
    const issue = await gh.getIssue(task.owner, task.repo, task.issueNumber)
    ctx = {
      id: taskId, owner: task.owner, repo: task.repo, issue,
      wt: git.worktreePathFor(taskId), branch: task.branch, base: task.base,
      model: task.model, phase: 'planning', plan: task.plan, lastText: task.plan,
    }
    sessions.set(taskId, ctx)
  }

  if (ctx.phase !== 'planning') return false
  ctx.phase = 'executing'
  const plan = ctx.plan || ctx.lastText

  addEvent(taskId, { kind: 'status', text: 'Plan approved — starting execution…' })
  if (ctx.handle) {
    ctx.handle.interrupt()
    ctx.handle.close()
    await ctx.handle.done.catch(() => {})
  }

  const ac = new AbortController()
  ctx.ac = ac
  await updateTask(taskId, { status: 'running', plan })

  // Run execution in the background; the HTTP request returns immediately.
  ;(async () => {
    try {
      const res = await runExecution({
        prompt: executePrompt(ctx.owner, ctx.repo, ctx.issue, plan),
        cwd: ctx.wt, model: ctx.model, signal: ac.signal,
        onEvent: (e) => addEvent(taskId, e),
        askUser: async (question) => {
          addEvent(taskId, { kind: 'question', text: question })
          await updateTask(taskId, { status: 'waiting', question })
          const reply = await questions.register(taskId)
          await updateTask(taskId, { status: 'running', question: null })
          addEvent(taskId, { kind: 'answer', text: reply })
          return reply
        },
      })
      await finalize(ctx, res)
    } catch (err) {
      console.error(`[exec ${taskId}]`, err)
      addEvent(taskId, { kind: 'error', text: err.message })
      await updateTask(taskId, { status: 'error', error: err.message })
      await git.removeWorktree(ctx.owner, ctx.repo, taskId).catch(() => {})
      sessions.delete(taskId)
    }
  })()
  return true
}

async function finalize(ctx, res) {
  const { id, owner, repo, wt, branch, base, issue } = ctx
  if (ctx.ac?.signal.aborted) {
    await updateTask(id, { status: 'cancelled' })
    await git.removeWorktree(owner, repo, id)
    sessions.delete(id)
    return
  }
  const summary = res.summary
  addEvent(id, { kind: 'status', text: 'Committing changes…' })
  await updateTask(id, { status: 'committing', summary, costUsd: res.costUsd })
  const committed = await git.commitAll(wt, `${issue.title}\n\nResolves #${issue.number}`)
  if (!committed) {
    addEvent(id, { kind: 'status', text: 'No file changes produced — nothing to push.' })
    await updateTask(id, { status: 'no_changes' })
    await git.removeWorktree(owner, repo, id)
    sessions.delete(id)
    return
  }
  addEvent(id, { kind: 'status', text: 'Pushing branch to origin…' })
  await updateTask(id, { status: 'pushing' })
  await git.pushBranch(wt, branch)

  addEvent(id, { kind: 'status', text: 'Opening pull request…' })
  await updateTask(id, { status: 'opening_pr' })
  const prUrl = await gh.createPr(owner, repo, {
    head: branch, base, title: issue.title, body: prBody(issue, summary, ctx.plan),
  })
  await updateTask(id, { status: 'pr_open', prUrl })
  addEvent(id, { kind: 'result', text: `Pull request opened → ${prUrl}`, ok: true })
  await git.removeWorktree(owner, repo, id)
  sessions.delete(id)
}

// --- Review flow ---

function reviewPrompt(owner, repo, pr, diff) {
  return `You are reviewing pull request #${pr.number} ("${pr.title}") in ${owner}/${repo}. The PR's head is already checked out in your current working directory.

The complete diff is provided below — that is your primary material. You may read files in the current directory (relative paths only) for surrounding context, but you do NOT need to explore much. You are already at the repo root: never cd elsewhere, use absolute paths, or access anything outside this directory — those attempts are blocked. Do NOT modify any files; this is review-only.

Review the diff for correctness bugs, security issues, and clear quality problems. Be specific, concise, and fair — skip nitpicks unless they matter.

Output your review as GitHub-flavored markdown:
- A one or two sentence overall summary.
- A "## Findings" section: one bullet per issue as **\`path:line\`** — _severity_ (bug / security / quality) — the problem and a concrete suggested fix. If you find no real issues, say so plainly.

--- DIFF ---
${diff}
--- END DIFF ---`
}

export async function startReview(task) {
  const { id, owner, repo, issueNumber: prNumber, model } = task
  try {
    await updateTask(id, { status: 'preparing' })
    addEvent(id, { kind: 'status', text: `Fetching PR #${prNumber}…` })
    const pr = await gh.getPr(owner, repo, prNumber)
    let diff = await gh.getPrDiff(owner, repo, prNumber)
    const MAX = 60000
    if (diff.length > MAX) {
      diff = diff.slice(0, MAX) + '\n…[diff truncated]…'
      addEvent(id, { kind: 'status', text: 'Large diff truncated for review.' })
    }

    addEvent(id, { kind: 'status', text: 'Checking out PR head in a worktree…' })
    const { path: wt } = await git.createPrWorktree(owner, repo, id, prNumber)
    await updateTask(id, { status: 'reviewing' })
    addEvent(id, { kind: 'status', text: `Reviewing #${prNumber}…` })

    const ac = new AbortController()
    sessions.set(id, { id, owner, repo, kind: 'review', prNumber, wt, ac })

    const res = await runExecution({
      prompt: reviewPrompt(owner, repo, pr, diff),
      cwd: wt, model, signal: ac.signal,
      onEvent: (e) => addEvent(id, e),
    })

    await git.removeWorktree(owner, repo, id) // review captured; no further fs needed
    if (ac.signal.aborted) {
      await updateTask(id, { status: 'cancelled' })
      sessions.delete(id)
      return
    }
    await updateTask(id, { status: 'reviewed', review: res.summary, costUsd: res.costUsd })
    addEvent(id, { kind: 'status', text: 'Review ready — approve to post it to the PR.' })
  } catch (err) {
    console.error(`[review ${id}]`, err)
    addEvent(id, { kind: 'error', text: err.message })
    await updateTask(id, { status: 'error', error: err.message })
    await git.removeWorktree(owner, repo, id).catch(() => {})
    sessions.delete(id)
  }
}

async function approveReview(taskId, task) {
  if (!task || task.status !== 'reviewed' || !task.review) return false
  const { owner, repo, issueNumber: prNumber, review } = task
  try {
    addEvent(taskId, { kind: 'status', text: 'Posting review to the PR…' })
    await updateTask(taskId, { status: 'posting' })
    const url = await gh.postPrComment(owner, repo, prNumber, `${review}\n\n---\n🤖 Reviewed by Squadron`)
    await updateTask(taskId, { status: 'review_posted', prUrl: url })
    addEvent(taskId, { kind: 'result', text: `Review posted → ${url}`, ok: true })
    sessions.delete(taskId)
    return true
  } catch (err) {
    addEvent(taskId, { kind: 'error', text: err.message })
    await updateTask(taskId, { status: 'error', error: err.message })
    return false
  }
}

export function cancel(taskId) {
  questions.clear(taskId)
  const ctx = sessions.get(taskId)
  if (!ctx) return false
  // Flip out of 'planning' first so the trailing 'result' from interrupting the
  // session is ignored by onPlanMessage (otherwise it resets status to 'planned').
  ctx.phase = 'cancelled'
  ctx.ac?.abort()
  ctx.handle?.interrupt()
  ctx.handle?.close()
  git.removeWorktree(ctx.owner, ctx.repo, taskId).catch(() => {})
  updateTask(taskId, { status: 'cancelled' })
  sessions.delete(taskId)
  return true
}
